[INFO 16:55:46] pymarl Running command 'my_main'
[INFO 16:55:46] pymarl Started run with ID "1"
[DEBUG 16:55:46] pymarl Starting Heartbeat
[DEBUG 16:55:46] my_main Started
[INFO 16:55:46] my_main Experiment Parameters:
[INFO 16:55:46] my_main 

{   'action_selector': 'epsilon_greedy',
    'add_value_last_step': True,
    'agent': 'rnn',
    'batch_size': 32,
    'batch_size_run': 32,
    'buffer_cpu_only': True,
    'buffer_size': 5000,
    'checkpoint_path': '',
    'common_reward': True,
    'env': 'gymma',
    'env_args': {   'key': 'warehouse_env:WarehouseEnvWithDynamicTasks',
                    'pretrained_wrapper': None,
                    'seed': 52748889,
                    'time_limit': 200},
    'epsilon_anneal_time': 50000,
    'epsilon_finish': 0.05,
    'epsilon_start': 1.0,
    'evaluate': False,
    'gamma': 0.99,
    'grad_norm_clip': 10,
    'hidden_dim': 64,
    'hypergroup': None,
    'label': 'default_label',
    'learner': 'q_learner',
    'learner_log_interval': 10000,
    'load_step': 0,
    'local_results_path': 'results',
    'log_interval': 50000,
    'lr': 0.0005,
    'mac': 'basic_mac',
    'mixer': 'qmix',
    'name': 'qmix_warehouse',
    'obs_agent_id': True,
    'obs_last_action': True,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'render': False,
    'repeat_id': 1,
    'reward_scalarisation': 'sum',
    'runner': 'parallel',
    'runner_log_interval': 10000,
    'save_model': False,
    'save_model_interval': 50000,
    'save_replay': False,
    'seed': 52748889,
    't_max': 200000,
    'target_update_interval_or_tau': 500,
    'test_greedy': True,
    'test_interval': 50000,
    'test_nepisode': 96,
    'use_cuda': True,
    'use_tensorboard': False,
    'use_wandb': False,
    'wandb_mode': 'offline',
    'wandb_project': None,
    'wandb_save_model': False,
    'wandb_team': None}

Process Process-1:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-2:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-3:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-4:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-5:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-6:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-7:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-8:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-9:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-10:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-11:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-12:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-13:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-14:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-15:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-16:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-17:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-18:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-19:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-20:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-21:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-22:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-23:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-24:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-25:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-26:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-27:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-28:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-29:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-30:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-31:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
Process Process-32:
Traceback (most recent call last):
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 502, in _find_spec
    importlib.import_module(module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'warehouse_env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 33, in gymma_fn
    return GymmaWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/gymma.py", line 39, in __init__
    self._env = gym.make(f"{key}", **kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 687, in make
    env_spec = _find_spec(id)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/epymarl_env/lib/python3.8/site-packages/gymnasium/envs/registration.py", line 504, in _find_spec
    raise ModuleNotFoundError(
ModuleNotFoundError: No module named 'warehouse_env'. Environment registration via importing a module failed. Check whether 'warehouse_env' contains env registration and can be imported.
