[INFO 13:30:00] pymarl Running command 'my_main'
[INFO 13:30:00] pymarl Started run with ID "1"
[DEBUG 13:30:00] pymarl Starting Heartbeat
[DEBUG 13:30:00] my_main Started
[INFO 13:30:00] my_main Experiment Parameters:
[INFO 13:30:00] my_main 

{   'action_selector': 'epsilon_greedy',
    'add_value_last_step': True,
    'agent': 'rnn',
    'batch_size': 32,
    'batch_size_run': 32,
    'buffer_cpu_only': True,
    'buffer_size': 5000,
    'checkpoint_path': '',
    'common_reward': True,
    'env': 'sc2',
    'env_args': {   'key': 'WarehouseEnv-v0',
                    'map_name': 'aaa',
                    'seed': 737746851,
                    'time_limit': 200},
    'epsilon_anneal_time': 50000,
    'epsilon_finish': 0.05,
    'epsilon_start': 1.0,
    'evaluate': False,
    'gamma': 0.99,
    'grad_norm_clip': 10,
    'hidden_dim': 64,
    'hypergroup': None,
    'label': 'default_label',
    'learner': 'q_learner',
    'learner_log_interval': 2000,
    'load_step': 0,
    'local_results_path': 'results',
    'log_interval': 2000,
    'lr': 0.0005,
    'mac': 'basic_mac',
    'mixer': 'qmix',
    'name': 'qmix_warehouse',
    'obs_agent_id': True,
    'obs_last_action': True,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'render': False,
    'repeat_id': 1,
    'reward_scalarisation': 'sum',
    'runner': 'parallel',
    'runner_log_interval': 2000,
    'save_model': False,
    'save_model_interval': 50000,
    'save_replay': False,
    'seed': 737746851,
    't_max': 200000,
    'target_update_interval_or_tau': 500,
    'test_greedy': True,
    'test_interval': 2000,
    'test_nepisode': 32,
    'use_cuda': True,
    'use_tensorboard': False,
    'use_wandb': False,
    'wandb_mode': 'offline',
    'wandb_project': None,
    'wandb_save_model': False,
    'wandb_team': None}

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-6:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-7:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-8:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-9:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-10:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-11:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-12:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-13:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-14:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-15:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-16:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-17:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-18:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-19:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-20:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-21:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-22:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-23:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-24:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-25:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-26:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-27:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-28:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-29:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-30:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-31:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
Process Process-32:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/runners/parallel_runner.py", line 290, in env_worker
    env = env_fn.x()
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/__init__.py", line 48, in smac_fn
    return SMACWrapper(**kwargs)
  File "/home/bhuv/Documents/bhuv-diffusion/epymarl/src/envs/smac_wrapper.py", line 8, in __init__
    self.env = StarCraft2Env(map_name=map_name, seed=seed, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'key'
